ALTER TABLE users
ALTER COLUMN user_creation_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE admins
ALTER COLUMN admin_creation_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE vets
ALTER COLUMN vet_creation_time SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE dogs
ALTER COLUMN dog_creation_time SET DEFAULT CURRENT_TIMESTAMP;
