# Ref1: https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: migrate-dev
run-name: ${{github.actor}} is developing the workfolw for running migrations against the dev database
on:
  push:
    branches:
      - main
      - deploy-dev
jobs:
  test-migrations:
    uses: ./.github/workflows/test-migrations.yml
  run-migrations:
    needs: [test-migrations]
    uses: ./.github/workflows/run-migrations.yml
    with:
      migrations_dir: migrations
    secrets:
      DB_HOST: ${{secrets.DEV_DB_HOST}}
      DB_PORT: ${{secrets.DEV_DB_PORT}}
      DB_USER: ${{secrets.DEV_DB_USER}}
      DB_PASSWORD: ${{secrets.DEV_DB_PASSWORD}}
      DB_NAME: ${{secrets.DEV_DB_NAME}}
