# Ref1: https://docs.github.com/en/actions/using-workflows/reusing-workflows
name: on-push-to-dev
run-name: ${{github.actor}} is deploying migrations to dev database
on:
  push:
    branches:
      - dev
jobs:
  test:
    uses: ./.github/workflows/x-test.yml
  migrate:
    needs: [test]
    uses: ./.github/workflows/x-migrate.yml
    with:
      migrations_dir: migrations
    secrets:
      DB_HOST: ${{secrets.DEV_DB_HOST}}
      DB_PORT: ${{secrets.DEV_DB_PORT}}
      DB_USER: ${{secrets.DEV_DB_USER}}
      DB_PASSWORD: ${{secrets.DEV_DB_PASSWORD}}
      DB_NAME: ${{secrets.DEV_DB_NAME}}
